-- 코드를 입력하세요
SELECT
    REST_INFO.FOOD_TYPE,
    REST_ID,
    REST_NAME,
    REST_INFO.FAVORITES
FROM
    REST_INFO
RIGHT JOIN (
    SELECT
        FOOD_TYPE,
        MAX(FAVORITES) AS 'FAVORITES'
    FROM
        REST_INFO
    GROUP BY
        FOOD_TYPE    
    ) AS TOP_RES
ON REST_INFO.FOOD_TYPE = TOP_RES.FOOD_TYPE AND REST_INFO.FAVORITES = TOP_RES.FAVORITES
ORDER BY
    FOOD_TYPE DESC