-- 코드를 입력하세요
SELECT
    FOOD_PRODUCT.CATEGORY,
    FOOD_PRODUCT.PRICE AS 'MAX_PRICE',
    FOOD_PRODUCT.PRODUCT_NAME
FROM
    FOOD_PRODUCT
LEFT JOIN (
    SELECT
        CATEGORY,
        MAX(PRICE) AS 'PRICE'
    FROM
        FOOD_PRODUCT
    GROUP BY
        CATEGORY
    ) AS maxprice
    ON FOOD_PRODUCT.CATEGORY = maxprice.CATEGORY
WHERE
    FOOD_PRODUCT.CATEGORY = maxprice.CATEGORY
    AND FOOD_PRODUCT.PRICE = maxprice.PRICE
    AND FOOD_PRODUCT.CATEGORY REGEXP '과자|국|김치|식용유'
ORDER BY
    MAX_PRICE DESC