-- 코드를 입력하세요
SELECT
    PRODUCT.PRODUCT_CODE,
    SUM(PRODUCT.PRICE * OFFLINE_SALE.SALES_AMOUNT) AS 'SALES'
FROM
    OFFLINE_SALE
LEFT JOIN PRODUCT
    ON OFFLINE_SALE.PRODUCT_ID = PRODUCT.PRODUCT_ID
GROUP BY
    PRODUCT_CODE
ORDER BY
    SALES DESC,
    PRODUCT_CODE ASC;