-- 코드를 입력하세요
SELECT
    FOOD_ORDER.PRODUCT_ID AS 'PRODUCT_ID',
    FOOD_PRODUCT.PRODUCT_NAME,
    SUM(FOOD_ORDER.AMOUNT * FOOD_PRODUCT.PRICE) AS 'TOTAL_SALES'
FROM
    FOOD_ORDER
LEFT JOIN FOOD_PRODUCT
    ON FOOD_ORDER.PRODUCT_ID = FOOD_PRODUCT.PRODUCT_ID
WHERE
    DATE_FORMAT(PRODUCE_DATE, '%Y-%m') = '2022-05'
GROUP BY
    PRODUCT_ID
ORDER BY
    TOTAL_SALES DESC,
    PRODUCT_ID

# SELECT *
# FROM FOOD_ORDER
# LEFT JOIN FOOD_PRODUCT
#     ON FOOD_ORDER.PRODUCT_ID = FOOD_PRODUCT.PRODUCT_ID
# WHERE
#     DATE_FORMAT(PRODUCE_DATE, '%Y-%m') = '2022-05'

# SELECT
#     *
# FROM FOOD_PRODUCT