-- 코드를 입력하세요
SELECT
    INFO.INGREDIENT_TYPE,
    SUM(FH.TOTAL_ORDER) AS TOTAL_ORDER
FROM
    FIRST_HALF FH
LEFT JOIN ICECREAM_INFO INFO
    ON FH.FLAVOR = INFO.FLAVOR
GROUP BY 
    INFO.INGREDIENT_TYPE
ORDER BY
    TOTAL_ORDER ASC;