-- 코드를 입력하세요
SELECT DISTINCT
    HIS.CAR_ID
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HIS
LEFT JOIN CAR_RENTAL_COMPANY_CAR AS CAR
    ON HIS.CAR_ID = CAR.CAR_ID
WHERE
    CAR_TYPE = '세단'
    AND START_DATE >= '2022-10-01'
ORDER BY
    CAR_ID DESC;