-- 코드를 입력하세요
SELECT
    info.REST_ID,
    REST_NAME,
    FOOD_TYPE,
    FAVORITES,
    ADDRESS,
    ROUND(AVG(REVIEW_SCORE), 2) AS 'SCORE'
FROM
    REST_INFO AS info
RIGHT JOIN REST_REVIEW AS rev
    ON info.REST_ID = rev.REST_ID
WHERE
    ADDRESS LIKE '서울%'
GROUP BY
    REST_ID
ORDER BY
    SCORE DESC,
    FAVORITES DESC

# SELECT
#     *
# FROM
#     REST_REVIEW
# RIGHT JOIN REST_INFO
#     ON REST_REVIEW.REST_ID = REST_INFO.REST_ID
# WHERE
#     ADDRESS REGEXP '서울'